CREATE TABLE tax_invoices (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    business_id BIGINT UNSIGNED NOT NULL,
    penda_invoice_id VARCHAR(255) NOT NULL UNIQUE,
    digitax_sales_id VARCHAR(255) UNIQUE,
    invoice_type ENUM('normal', 'credit_note', 'debit_note', 'proforma', 'lpo', 'export') DEFAULT 'normal',
    invoice_number VARCHAR(100),
    customer_tpin VARCHAR(10),
    customer_name VARCHAR(255),
    customer_email VARCHAR(255),
    customer_phone VARCHAR(50),
    invoice_date DATE NOT NULL,
    total_amount DECIMAL(15, 2) NOT NULL,
    tax_amount DECIMAL(15, 2) NOT NULL,
    discount_amount DECIMAL(15, 2) DEFAULT 0,
    receipt_number VARCHAR(100),
    serial_number VARCHAR(100),
    receipt_signature TEXT,
    receipt_url TEXT,
    internal_data TEXT,
    receipt_qr_code TEXT,
    queue_status ENUM('queued', 'processing', 'complete', 'failed') DEFAULT 'queued',
    sync_status ENUM('pending', 'syncing', 'synced', 'failed') DEFAULT 'pending',
    sales_tax_summary JSON,
    digitax_response JSON,
    error_message TEXT,
    callback_url VARCHAR(500),
    synced_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
    INDEX idx_penda_invoice (penda_invoice_id),
    INDEX idx_digitax_sales (digitax_sales_id),
    INDEX idx_queue_status (queue_status),
    INDEX idx_sync_status (sync_status),
    INDEX idx_invoice_date (invoice_date)
);
