CREATE TABLE tax_items (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    business_id BIGINT UNSIGNED NOT NULL,
    penda_product_id VARCHAR(255) NOT NULL,
    digitax_item_id VARCHAR(255) UNIQUE,
    item_name VARCHAR(255) NOT NULL,
    item_code VARCHAR(100),
    item_class_code VARCHAR(20) NOT NULL,
    item_type_code VARCHAR(10) NOT NULL,
    unit_of_measure VARCHAR(50),
    is_stockable BOOLEAN DEFAULT false,
    default_price DECIMAL(15, 2),
    tax_type_code VARCHAR(10) NOT NULL,
    sync_status ENUM('pending', 'syncing', 'synced', 'failed') DEFAULT 'pending',
    digitax_response JSON,
    error_message TEXT,
    synced_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
    INDEX idx_penda_product (penda_product_id),
    INDEX idx_digitax_item (digitax_item_id),
    INDEX idx_sync_status (sync_status)
);
